### PR TITLE
Added namespace & Dom verification #3

### PR DESCRIPTION
**Pull request by rulerofthedeities**
- added namespace so that it won't conflict with existing code
- verify if DOM is loaded so that it also works in the header or in an external js file

### CODE REVIEW

**Comment by rulerofthedeities** [comment]
PS: I thought I'd chime in after I saw your post on webmasterworld.

**Comment by envintus** [comment]
Awesome, I'll take a look at it later tonight. Thank you!

**Comment by envintus** [comment]
I reconciled the conflicts and merged your changes with master. I'll tag it as 1.1 in a bit. Thanks again for making this better!

**Comment by envintus** [comment]
Thought I'd comment here, but I did not see any additional way to handle this commit via Github's interface after reconciling the merge conflicts locally. If "Closing" the pull request was not the couth thing to do in this scenario, then just let me know. Master is now tagged at 1.1 with your enhancements.

**Comment by rulerofthedeities** [comment]
All fine, thanks, should have made the pull request before you removed the script tag but I noticed it too late.

Hope you're happy with the modifications - you don't have to implement them all. (I'm not too happy with the IE8 fallback myself, would prefer a catch-all situation. I usually do that with jquery and found no better solution :( ).

**Comment by envintus** [comment]
Sounds good and thanks for the quick feedback. I'm very happy with what you've done!

**Pull request closed without merging**
